# Generated by Django 5.0.1 on 2025-03-07 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phonenumber', models.IntegerField()),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Image', models.ImageField(null=True, upload_to='Image')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Dept', models.CharField(max_length=200, null=True)),
                ('Year', models.CharField(max_length=200, null=True)),
                ('logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
