# Generated by Django 5.0.1 on 2025-03-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_reg',
            new_name='Student_reg',
        ),
    ]
