# Generated by Django 5.0.1 on 2025-03-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_reg_student_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GName', models.CharField(max_length=100)),
                ('GEmail', models.EmailField(max_length=254, unique=True)),
                ('GPhone', models.CharField(max_length=15)),
                ('GPassword', models.CharField(max_length=50, null=True)),
                ('GDepartment', models.CharField(max_length=100)),
                ('GExperience', models.IntegerField()),
                ('GImage', models.ImageField(null=True, upload_to='Image')),
                ('logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
