# Generated by Django 5.0.1 on 2025-03-08 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_reg',
            name='gid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.guide'),
        ),
    ]
