# Generated by Django 5.0.1 on 2025-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_reg_gid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering')], max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('submission_date', models.DateField()),
                ('submission_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('document_type', models.CharField(choices=[('Hardcopy', 'Hardcopy'), ('Softcopy', 'Softcopy')], max_length=10)),
                ('first_review_date', models.DateField()),
                ('second_review_date', models.DateField()),
                ('third_review_date', models.DateField()),
            ],
        ),
    ]
