# Generated by Django 5.0.1 on 2025-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_projectsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='document_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='submission_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
