# Generated by Django 5.0.1 on 2025-03-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_projectsubmission_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('abstract_file', models.FileField(upload_to='abstracts/')),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('gid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.guide')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student_reg')),
            ],
        ),
    ]
