# Generated by Django 5.0.1 on 2025-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_projectabstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectabstract',
            name='status',
            field=models.CharField(default='Uploaded', max_length=10),
        ),
    ]
