# Generated by Django 5.0.1 on 2025-03-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_projectabstract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_revmark', models.CharField(max_length=100)),
                ('review1_date', models.DateField(auto_now_add=True)),
                ('first_pfffile', models.FileField(blank=True, null=True, upload_to='reviews/first/')),
                ('first_docfile', models.FileField(blank=True, null=True, upload_to='reviews/first/')),
                ('fstatus', models.CharField(default='Uploaded', max_length=100)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guide')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectabstract')),
                ('subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectsubmission')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_reg')),
            ],
        ),
        migrations.CreateModel(
            name='SecondReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_revmark', models.CharField(max_length=100)),
                ('review2_date', models.DateField(auto_now_add=True)),
                ('excelfile', models.FileField(blank=True, null=True, upload_to='reviews/second/')),
                ('pptfile', models.FileField(blank=True, null=True, upload_to='reviews/second/')),
                ('Sstatus', models.CharField(default='Uploaded', max_length=100)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guide')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectabstract')),
                ('subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectsubmission')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_reg')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_revmark', models.CharField(max_length=100)),
                ('review3_date', models.DateField(auto_now_add=True)),
                ('zipfile', models.FileField(blank=True, null=True, upload_to='reviews/third/')),
                ('tstatus', models.CharField(default='Uploaded', max_length=100)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guide')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectabstract')),
                ('subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectsubmission')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_reg')),
            ],
        ),
    ]
