# Generated by Django 5.0.1 on 2025-03-08 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_firstreview_secondreview_thirdreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstreview',
            name='subid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectsubmission'),
        ),
    ]
