# Generated by Django 5.0.1 on 2025-03-08 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_firstreview_subid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstreview',
            name='gid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.guide'),
        ),
        migrations.AlterField(
            model_name='firstreview',
            name='proid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectabstract'),
        ),
        migrations.AlterField(
            model_name='firstreview',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student_reg'),
        ),
        migrations.AlterField(
            model_name='secondreview',
            name='gid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.guide'),
        ),
        migrations.AlterField(
            model_name='secondreview',
            name='proid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectabstract'),
        ),
        migrations.AlterField(
            model_name='secondreview',
            name='subid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectsubmission'),
        ),
        migrations.AlterField(
            model_name='secondreview',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student_reg'),
        ),
        migrations.AlterField(
            model_name='thirdreview',
            name='gid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.guide'),
        ),
        migrations.AlterField(
            model_name='thirdreview',
            name='proid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectabstract'),
        ),
        migrations.AlterField(
            model_name='thirdreview',
            name='subid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectsubmission'),
        ),
        migrations.AlterField(
            model_name='thirdreview',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student_reg'),
        ),
    ]
