# Generated by Django 5.0.1 on 2025-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_firstreview_gid_alter_firstreview_proid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstreview',
            name='Review_Type1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secondreview',
            name='Review_Type2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thirdreview',
            name='Review_Type3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
