# Generated by Django 4.2.1 on 2025-03-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_reg',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
