# Generated by Django 4.2.3 on 2025-03-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_student_reg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstreview',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='firstreview',
            name='proid',
        ),
        migrations.RemoveField(
            model_name='firstreview',
            name='subid',
        ),
        migrations.RemoveField(
            model_name='firstreview',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='logid',
        ),
        migrations.RemoveField(
            model_name='projectabstract',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='projectabstract',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='secondreview',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='secondreview',
            name='proid',
        ),
        migrations.RemoveField(
            model_name='secondreview',
            name='subid',
        ),
        migrations.RemoveField(
            model_name='secondreview',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='thirdreview',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='thirdreview',
            name='proid',
        ),
        migrations.RemoveField(
            model_name='thirdreview',
            name='subid',
        ),
        migrations.RemoveField(
            model_name='thirdreview',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='student_reg',
            name='gid',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='FirstReview',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='ProjectAbstract',
        ),
        migrations.DeleteModel(
            name='ProjectSubmission',
        ),
        migrations.DeleteModel(
            name='SecondReview',
        ),
        migrations.DeleteModel(
            name='ThirdReview',
        ),
    ]
